[params]
  [params.jsonld]
    template = "website"
    logo = "**/logo.{svg,webp,png,jpg,jpeg,gif,bmp}"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"